services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://db:27017/taskflow

  db:
    image: mongo
    container_name: taskflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: